dart/lib/src/interfaces.dart, dart/lib/webdriver.dart, dart/pubspec.yaml, dart/test/pageloader_test.dart
Implement support for using eventTarget in WebDriverPageLoader (was
previously supported in HtmlPageLoader).
=> Add eventTarget to up and down methods on PageLoaderMouse.

dart/lib/sync/html.dart, dart/lib/sync/src/interfaces.dart, dart/lib/sync/webdriver.dart, dart/pubspec.yaml, dart/test/async/src/errors.dart, dart/test/async/src/html_pageloader.dart, dart/test/sync/html_no_shadow_dom_test.dart, dart/test/sync/html_test.dart, dart/test/sync/page_objects.dart, dart/tool/travis.sh
- Enable option in HtmlPageLoader.
- Since WebDriverPageLoader doesn't sync, option is no-op there.
Change travis script to use tuneup to analyze files.
Increment pubspec versions.
Disable keypress tests on dartium.
=> Add option to functions that sync to allow syncing to be disabled.

dart/lib/async/html.dart, dart/lib/async/src/core.dart, dart/test/async/src/errors.dart, dart/test/async/src/html_pageloader.dart
- improve exceptions stack traces when creating page objects
Old:
```
PageLoaderException: Unable to load field Symbol("doesntExist") caused by
Bad state: No element
#0      _FieldInfo.setField.<setField_async_body> (package:pageloader/async/src/core.dart:323:7)
#1      _asyncCatchHelper.<anonymous closure> (dart:core-patch/core_patch.dart:14)
#2      StackZoneSpecification.registerBinaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:145:26)
#3      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:205:15)
#4      StackZoneSpecification.registerBinaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:145:14)
#5      _rootRunBinary (dart:async/zone.dart:923)
#6 …
```
=> Improve exceptions in async PageLoader.

dart/lib/async/html.dart
The old approach of using textInput events worked for type() but not for
clear(). It looks like textInput events with an empty data field don't
publish the expected browser events, so anything listening for changes
to the element's value (e.g. Angular) wouldn't see anything.
Firing "input" and "change" should give the expected behavior: "input"
to trigger on-keypress handlers, and "change" to trigger on-enter
handlers.
=> Fire input/change events from type() and clear().

dart/lib/async/src/interfaces.dart, dart/lib/async/webdriver.dart
html.dart's `moveTo` takes an `eventTarget` parameter, which is not specified in the interface of `PageloaderMouse`. This PR fixes that and also adds the parameter to webdriver.dart for consistency
=> fix analyzer warnings

dart/async/pubspec.yaml
There has been some unhappiness about how we use version numbers for this package. My suggestion is: The next release should be version 2.0.0 and we then use semantic versioning (http://semver.org/) going forward.
=> Bump async version to 2.0.0

dart/async/lib/src/core.dart
Improve 'No element' error message by showing the finder (e.g. ensureTag('item')).
=> Improve 'No element' error message.

dart/async/lib/html.dart, dart/async/lib/src/annotations.dart, dart/async/lib/src/core.dart, dart/async/lib/src/interfaces.dart, dart/async/lib/webdriver.dart, dart/async/pubspec.yaml
This prevents out-of-order execution (and RPCs) that are caused by async* generators not blocking.
This is a short-term fix that will allow us to use awaitChecking in the webdriver.
=> Use for ... await ... toList instead of await for

dart/async/lib/webdriver.dart
Fixing:
> [error] Could not infer type parameter T, dynamic must be of type num.
=> Fix strong-mode errors in webdriver.dart

.travis.yml, dart/async/lib/html.dart, dart/sync/lib/html.dart
This removes the use of KeyEvent which is broken in both Dartium (where it seems to silently fail) and DDC (where it creates a runtime type error).
=> Remove broken KeyEvent use

dart/async/lib/html.dart
This is a little more efficient and produces the same result.
=> Use String.length instead of String.codeUnits.length

dart/async/lib/html.dart, dart/async/lib/src/core.dart, dart/async/lib/src/interfaces.dart, dart/async/lib/webdriver.dart
In DDC 1.23.0-dev.11, `_ClassInfo`'s factory constructor can result in runtime errors, because of changes to inference. Basically, the `_classInfoCache` is declared to be a `Map<ClassMirror, _ClassInfo>`, where `_ClassInfo`'s type is unbound. So when the factory constructor is first called, say with `_ClassInfo<X>`, and the first entrant makes its way into `_classInfoCache`, then DDC is binding the type parameters to `Map<ClassMirror, _ClassInfo<X>>`. So then the second time the factory constructor is called, if it is with `_ClassInfo<Y>`, then Y was expected to be X ,and a runtime error is thrown.
This was tested on code in Google, and it looks good.
The only lines changed in the factory constructor are lines 102, 103, and 104. The rest are the result of dartfmt, which GitHub …
=> async: Uncomment generics, and fix DDC 1.23.0-dev.11 issue

build.yaml
A target with the default name is supposed to be required by
`build_config` but the check was missing.
See https://github.com/dart-lang/build/issues/1426
=> Use the default target name

README.md, build.yaml, lib/src/webdriver/webdriver_page_loader_element.dart
Adding a temporary restriction until build_runner's long-term solution is implemented. This should avoid the need for users to have a `build.yaml`.
Also minor fix with dart 2 runtime that will occur in a future sdk version.
=> New temporary file restriction

lib/src/api/exceptions.dart, lib/src/html/html_page_loader_element.dart, lib/src/webdriver/webdriver_page_loader_element.dart, lib/utils.dart
Improve logic on pageloader utils and matchers.
`exists` method on `PageLoaderElement` no longer throws an error when... it doesn't exist. Weird subroutine logic made it throw an error when `0 elements are found` - indicating the element doesn't exist. In other words, `exists` should just return `false`. This has been fixed. (All other method/getter calls to the element will still throw error though.)
For utils and methods, any `PageLoaderElement` based methods will perform two checks:
1. Ensure that either a `PageLoaderElement` or some PageObject is passed.
2. If (1) is satisfied, ensure that it exists. If it doesn't exist, throw an error indicating that a method was called on a non-existent `PageLoaderElement`.
Failures and errors will be more specific now.
=> Fix utils/matcher

lib/src/api/annotations.dart, lib/src/api/exceptions.dart, lib/src/html/html_page_loader_element.dart, lib/src/webdriver/webdriver_page_loader_element.dart, lib/utils.dart, test/data/html_setup.dart, test/data/webdriver_test_page.html, test/examples/correct/unannotated.g.dart, test/src/annotations.dart, test/src/annotations.g.dart, test/src/basic.dart
@ByDebugId now, by default, tries to match on 'debugid'/'debug-id'/'debugID'. Now adding in optional named parameters make it exclusively match on the passed variant of debugid.
Utils and matchers now no-longer swallows errors and behaves more exactly.
=> Change @ByDebugId and utils/matchers

pubspec.yaml, test/mocks/sdk.dart
The analyzer only supports strong mode now, and analyzer version
0.33.* will remove this constructor parameter.  As of analyzer version
0.32.5, the parameter is optional, so we can stop passing it now.
Also fix the pubspec to include the analyzer as a dev_dependency
(necessary because tests use the analyzer directly).
=> Stop passing strong parameter to SummaryBuilder constructor.

lib/src/api/page_loader_element_interface.dart
*   Change `text content` => `inner text` (textContent is a different element property)
*   Update link
Part of https://github.com/google/pageloader/issues/166
=> Fix `PageLoaderElement.innerText` doc.

pubspec.yaml
Looks like I can't use a solid ^0.34.0 due to built_value_generator. This should be a good middle ground solution until that is also bumped as well. #169
=> Bump analyzer to 0.34

README.md
Some markdown renderers require the newline before code blocks.
=> Fix formatting of "Inheritance" section.

CHANGELOG.md, pubspec.yaml
I'm skipping from `>=2.0.0` to `>=2.2.0`, do you think this is fine Kevin? Or should I add an intermediary version for `>=2.1.0`?
=> Bump SDK and analyzer version

lib/src/generators/pageobject_generator.dart
This was a temporary analyzer API; it has been deprecated and replaced
by a method in AnalysisSession.
=> Stop making use of the `tmp` constructor for `ResolvedLibraryResultImpl`.

lib/src/api/annotations.dart, test/data/html_setup.dart, test/data/webdriver_test_page.html, test/src/annotations.dart
Create a `@ByTestId` annotation that selects element with attribute `data-test-id`.
Rationale behind this proposal:
Currently lots of test selectors are written using (layers of) css classes, tightly coupling tests to component styles and DOM structure, making them very brittle.
I'm working on a draft Testing on the Toilet episode that explains this problem in further detail. [go/change-resilient-ui-testing-tott](https://goto.google.com/change-resilient-ui-testing-tott)
Adding a `data-test-id` attribute to an element to help target-select it in tests is the solution we came to at Firebase console's design review. It allows a change-resilient way of writing selectors that survive any style changes or DOM restructuring. The original design doc is here: …
=> Create a @ByTestId annotation that selects element with attribute "data-test-id".
