google/pageloader

dart/lib/src/annotations.dart
dart/lib/webdriver.dart
dart/test/page_objects.dart
dart/test/pageloader_test.dart

Fix bug in PageLoaderMouse.up() for WebDriver with EventTarget.

Add @Global annotation.

---

dart/pubspec.yaml
dart/test/pageloader_test.dart

Update pubspec.yaml with new version numbers.

Fix EnsureTag tests.

---

dart/lib/html.dart
dart/lib/src/core.dart
dart/pubspec.yaml
dart/test/html_test.dart
dart/test/page_objects.dart
dart/test/pageloader_test.dart
dart/test/test_page.html

Clean up some formatting with dartformat
Upgrade version number.

Fix .type() method in HtmlPageLoader to work with TextAreaElements.

---

dart/lib/html.dart
dart/test/pageloader_test.dart

Fix bug in string normalization code.

---

dart/lib/async/webdriver.dart
dart/test/sync/html_no_shadow_dom_test.dart
dart/test/sync/html_test.dart

Delete unused classes in sync HTML tests.
Fix async element.shadowRoot.

Minor fixes

---

dart/lib/async/src/core.dart
dart/pubspec.yaml
dart/test/async/webdriver_no_shadow_dom_test.dart
dart/test/async/webdriver_test.dart

Uncomment exception handling block in sync pageloader.

---

dart/pubspec.yaml
dart/test/async/src/mouse.dart
dart/test/sync/pageloader_test.dart
dart/tool/travis.sh

Some travis config improvements.

Migrate to new version of pageloader.

---

dart/lib/async/html.dart
dart/lib/async/src/annotations.dart
dart/lib/async/src/core.dart
dart/lib/async/src/interfaces.dart
dart/lib/async/webdriver.dart
dart/lib/sync/src/core.dart
dart/lib/sync/webdriver.dart
dart/pubspec.yaml
dart/test/async/src/annotations.dart
dart/test/async/src/errors.dart
dart/test/async/src/html_pageloader.dart
dart/test/async/src/mouse.dart
dart/test/async/src/shadow_dom.dart
dart/test/data/html_no_shadow_dom_setup.dart
dart/test/data/html_setup.dart
dart/test/sync/html_no_shadow_dom_test.dart
dart/test/sync/html_test.dart
dart/test/sync/page_objects.dart
dart/test/sync/pageloader_test.dart

format with new version of dartfmt.
Make sync PageLoader's waiting work with both unittest and matcher Matchers.

Add new blur() and focus().

---

dart/lib/async/html.dart
dart/pubspec.yaml

Upgrade versions numbers.
Format with dartformat 0.2.0

Fix analyzer error in html.dart.

---

dart/lib/async/html.dart
dart/lib/async/src/interfaces.dart
dart/lib/async/webdriver.dart
dart/pubspec.yaml

add offset and getBoundingClientRect

---

dart/lib/async/html.dart
dart/lib/async/src/interfaces.dart
dart/lib/async/webdriver.dart
dart/pubspec.yaml

adding focusBefore parameter to type and clear

---

dart/lib/async/html.dart
dart/lib/async/src/interfaces.dart
dart/lib/async/webdriver.dart
dart/test/async/src/basic.dart

add isFocused

---

dart/lib/async/html.dart

add mouse down/up events to click in html.dart

---

dart/lib/async/html.dart
dart/lib/async/src/interfaces.dart
dart/lib/async/webdriver.dart
dart/pubspec.yaml
dart/test/async/src/mouse.dart

fixes b/26664638
This PR depends on https://github.com/google/webdriver.dart/pull/109, which has to be merged first!

adding enum for mouse buttons

---

dart/async/pubspec.yaml
dart/async/test/html_no_shadow_dom_test.dart
dart/async/test/html_test.dart
dart/async/test/setup/html_test_setup.dart
dart/async/test/setup/webdriver_test_setup.dart
dart/async/test/webdriver_no_shadow_dom_test.dart

This makes it a little easier to run the tests internally.

refactored test setup

---

dart/async/lib/html.dart
dart/async/lib/src/annotations.dart
dart/async/lib/src/interfaces.dart
dart/async/lib/webdriver.dart
dart/async/test/src/annotations.dart
dart/async/test/src/attributes.dart
dart/async/test/src/html_pageloader.dart
dart/async/test/src/typing.dart

- deprecate attributes getter.
- change all uses of attributes to seleniumAttributes.

Add new seleniumAttributes getter.

---

WORKSPACE
dart/async/BUILD
dart/async/pubspec.yaml

Update pub and bazel dependency versions.

Preparation for release 2.2.5.

---

dart/async/lib/html.dart
dart/async/lib/src/annotations.dart
dart/async/lib/src/interfaces.dart
dart/async/lib/webdriver.dart
dart/async/test/src/annotations.dart
dart/async/test/src/attributes.dart
dart/async/test/src/common.dart
dart/async/test/src/errors.dart
dart/async/test/src/html_pageloader.dart
dart/async/test/src/mouse.dart
dart/async/test/src/properties.dart
dart/async/test/src/selenium_attributes.dart
dart/async/test/src/shadow_dom.dart
dart/async/test/src/typing.dart

- Deprecate seleniumAttributes.

Add properties and attributes fields.

---

dart/async/lib/webdriver.dart

In some exotic cases (IE) the WebDriver spec doesn't seem to be supported as written here.
To avoid breakages, we do not rely on the syncdriver implementation at all when using the standard async constructor.

Separate async/sync completely.

---

analysis_options.yaml
lib/src/api/annotations.dart
lib/src/debug/performance/event.dart
lib/src/generators/methods/iterable_finder_method.dart
lib/src/generators/methods/list_finder_method.dart
lib/src/generators/methods/single_finder_method.dart
lib/src/generators/pageobject_generator.dart
lib/src/html/html_mouse.dart
lib/src/html/html_page_loader_element.dart
test/setup/io_config.dart
test/src/shared_list_page_objects.dart
test/src/shared_page_objects.dart

Cleaning up some lint warnings.

Lint warning cleanup

---

README.md
build.yaml

Add concrete examples for HtmlPageLoaderElement and WebdriverPageLoaderElement. Also add section on existence checking which also changed since version 2.
Issue #127

Update the documentation

---

CHANGELOG.md
pubspec.yaml

Update changelog and pubspec.yaml.

Preparation for 3.0.0 release

---

pubspec.yaml

Duplicate of PR: #188
Duplicated since travis was not being updated and tests failing.

Remove build_config - not needed.

---

pubspec.yaml

Set version range for `build_config`

---

CHANGELOG.md
pubspec.yaml

Bump analyzer to up to 0.40.0.
